language: php

services:
  - docker

before_install:
  - docker build -t flyimg .
  - docker run -t -d -i -v $(pwd):/var/www/html --name flyimg flyimg
  - docker exec flyimg composer install

script:
  - docker exec flyimg vendor/bin/phpunit
  - docker exec flyimg vendor/bin/phpcs --standard=PSR2 src/

notifications:
  email:
    - sadoknet@gmail.com
    - baamenabar@gmail.com
