home:
   path : /
   defaults: { _controller: 'Flyimg\App\Controller\DefaultController::indexAction' }

upload:
   path : /upload/{options}/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\DefaultController::uploadAction', imageSrc: '' }
   requirements:
      imageSrc: .+
path:
   path : /path/{options}/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\DefaultController::pathAction', imageSrc: '' }
   requirements:
      imageSrc: .+
